### ISSUE TITLE
Handwritten Digit classification 

### ISSUE THREAD

**Issue by praggyaverma** [SnowScriptWinterOfCode/JupyterNbk_Models#4]
Create a model that classifies handwritten digits using the MNIST dataset

**Comment by praggyaverma** [comment]
Hi moderator @tejaswi0910 ! I would like to work on this project. Please assign it to me

**Comment by tejaswi0910** [comment]
Squashed and merged all the 8 commits into a single commit in the base branch.
Thankyou for contributing Praggya
