### ISSUE TITLE
MRI Brain Tumor Classification

### ISSUE THREAD

**Issue by ShaikArshidBanu** [SnowScriptWinterOfCode/JupyterNbk_Models#6]
Description: 
Classify brain MRI images into tumor and non-tumor categories. This project is relevant for medical image analysis and diagnostics.

This involves using CNN Models to classify the images in to tumor or non-tumor categories.

**Comment by ShaikArshidBanu** [comment]
@tejaswi0910 @Nitya-Pasrija please assign this issue to me.

**Comment by tejaswi0910** [comment]
Thankyou for contributing!
Closing the issue now
