### ISSUE TITLE
BIRDS 525 SPECIES IMAGE CLASSIFICATION

### ISSUE THREAD

**Issue by sripriyaagarwal16** [SnowScriptWinterOfCode/JupyterNbk_Models#7]
Description:
To classify the 525 species of birds with testing ,training and validation dataset using image classification

**Comment by sripriyaagarwal16** [comment]
@tejaswi0910 please assign me the issue.

**Comment by sripriyaagarwal16** [comment]
@tejaswi0910 please assign me this issue.

**Comment by tejaswi0910** [comment]
Assigned the issue to you! Go ahead and start working :)

**Comment by sripriyaagarwal16** [comment]
Thank u di
