### ISSUE TITLE
Employee attendance management system using Face Recognition . 

### ISSUE THREAD

**Issue by jhakrishan20** [SnowScriptWinterOfCode/JupyterNbk_Models#9]
I am willing to implement an Employee attendance management system using face Recognition as a web application and securely saving the data in the database using Tensorflow.js and Ml5.js . So , please @tejaswi0910 assign me this issue .

**Comment by tejaswi0910** [comment]
Assigning this issue to you, please go ahead and start working!

**Comment by jhakrishan20** [comment]
@tejaswi0910 Thank you for assigning

**Comment by tejaswi0910** [comment]
@jhakrishan20, kindly make sure that you are submitting the repo before the deadline.

**Comment by jhakrishan20** [comment]
@tejaswi0910  I am very sorry for the delay to make the PR as I was busy with my college practicals , I am almost done with my model and will make the PR tonight.

**Comment by jhakrishan20** [comment]
I made the PR , kindly review it #18

**Comment by tejaswi0910** [comment]
thankyou for contributing!! Closing the issue now
